routes/web.php
<?php

use Illuminate\Support\Facades\Auth;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get(
    '/', function () {
    return view('welcome');
}
);

Route::group(
    [
        'namespace' => 'Admin',
        'prefix'    => 'admin',
        'as'        => 'admin.',

    ], function () {
        Auth::routes();
        Route::group(
            [
                'middleware' => [
                    'auth:admin',
                ],
            ], function () {
            Route::get('/', 'AdvertController@index');
            Route::any('users/find', 'UserController@find')->name('users.find');
            Route::post('adverts/destroy-photo/', 'AdvertController@destroyPhoto')->name('adverts.destroyPhoto');
            Route::resource('adverts', 'AdvertController');
            Route::resource('users', 'UserController');
            Route::resource('regions', 'RegionController');
            Route::resource('categories', 'CategoryController');
        }
    );
}
);

Route::group(
    [
        'namespace' => 'Frontend',
        //'prefix' => 'frontend',
        'as'        => 'frontend.'
        //'middleware' => 'auth'
    ], function () {
    Auth::routes();
    Route::get('/', 'SiteController@index')->name('index');
    Route::get('/feedback', 'SiteController@feedback')->name('feedback');
    Route::post('/feedback', 'SiteController@sendFeedback')->name('send-feedback');
    Route::post('region/session', 'SiteController@session')->name('session');
    Route::get('search', 'AdvertController@search')->name('adverts.search');
    Route::get('{type}/{category?}', 'AdvertController@index')
        ->where(
            [
                'type' => 'donate|receive',
                'category' => '(\w|-)+',
            ]
        )
        ->name('adverts.index');
    Route::resource('adverts', 'AdvertController')->only(
        [
            'show',
        ]
    );
    Route::resource('advert-user', 'AdvertUserController');
    Route::delete('advert-user/delete-photo/{photo}', 'AdvertUserController@deletePhoto')->name(
        'advert-user.delete-photo'
    );
    Route::resource('favorites', 'FavoriteController');
}
);

app/Models/common/Region.php
<?php

namespace App\Models\common;

use Cviebrock\EloquentSluggable\Sluggable;
use Illuminate\Contracts\Pagination\LengthAwarePaginator;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Collection;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Carbon;
use Kyslik\ColumnSortable\Sortable;

/**
 * Class Region
 *
 * @package App
 *
 * @property int                          $id
 * @property mixed                        status
 * @property string                       $title
 * @property string                       $slug
 * @property Carbon|null                  $created_at
 * @property Carbon|null                  $updated_at
 *
 * @property-read \App\Models\common\User $user
 *
 * @mixin \Eloquent
 *
 * @author Dimus <iron@te.net.ua>
 */
class Region extends Model
{
    use Sluggable;
    use Sortable;

    /**
     * Region status active
     */
    const STATUS_ACTIVE = 'active';
    /**
     * Region status inactive
     */
    const STATUS_INACTIVE = 'inactive';

    /**
     * Fillable attr
     *
     * @var array
     */
    protected $fillable = ['title', 'status'];
    /**
     * Sortable attr
     *
     * @var array
     */
    public $sortable = ['id', 'title'];

    /**
     * Get all region statuses
     *
     * @return array
     */
    public static function getStatuses()
    {
        return [
            self::STATUS_ACTIVE,
            self::STATUS_INACTIVE,
        ];
    }

    /**
     * Search region by params
     *
     * @param array $params   params for searching
     * @param bool  $sortable flag
     * @param null  $paginate flag
     *
     * @return LengthAwarePaginator|Builder[]|Collection
     */
    public static function search($params, $sortable = true, $paginate = null)
    {
        $model = new self();

        if ($sortable) {
            $query = self::sortable();
        } else {
            $query = $model->newQuery();
        }
        if ($value = array_get($params, 'id')) {
            $query->where('id', $value);
        }
        if ($value = array_get($params, 'title')) {
            $query->where('title', 'like', $value . '%');
        }
        if ($value = array_get($params, 'status')) {
            $query->where('status', $value);
        }
        if ($paginate) {
            return $query->paginate($paginate);
        } else {
            return $query->get();
        }
    }

    /**
     * Return the sluggable configuration array for this model.
     *
     * @return array
     */
    public function sluggable()
    {
        return [
            'slug' => [
                'source' => 'title',
            ],
        ];
    }

    /**
     * Get related user
     *
     * @return \Illuminate\Database\Eloquent\Relations\HasOne
     */
    public function user()
    {
        return $this->hasOne(User::class);
    }

    /**
     * Determine if region is active
     *
     * @return bool
     */
    public function isActive()
    {
        return $this->status == self::STATUS_ACTIVE;
    }
}

app/Http/Controllers/Admin/RegionController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\RegionCreateRequest;
use App\Http\Requests\RegionUpdateRequest;
use App\Http\Services\RegionService;
use App\Models\common\Region;
use Illuminate\Http\Request;

/**
 * Class RegionController
 *
 * @package App\Http\Controllers\Admin
 * @author  Dimus <iron@te.net.ua>
 */
class RegionController extends Controller
{
    /**
     * Region service instance
     *
     * @var \App\Http\Services\RegionService
     */
    private $_regionService;

    /**
     * RegionController constructor.
     *
     * @param RegionService $regionService instance
     */
    public function __construct(RegionService $regionService)
    {
        $this->_regionService = $regionService;
    }

    /**
     * Display a listing of the resource.
     *
     * @param Request $request
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $regions = Region::search($request, true, 15);
        $statuses = $this->_regionService->getAllStatuses();
        return view('admin.regions.index', compact('statuses', 'regions'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $statuses = $this->_regionService->getAllStatuses();
        return view('admin.regions.create', compact('statuses'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param RegionCreateRequest $request
     *
     * @return \Illuminate\Http\Response
     */
    public function store(RegionCreateRequest $request)
    {
        Region::create(
            [
                'status' => $request->status,
                'title' => $request->title,
            ]
        );
        return redirect()->route('admin.regions.index');
    }

    /**
     * Display the specified resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function show()
    {
        return view('admin.regions.show');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param Region $region
     *
     * @return \Illuminate\Http\Response
     */
    public function edit(Region $region)
    {
        $statuses = $this->_regionService->getAllStatuses();
        return view('admin.regions.edit', compact('region', 'statuses'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param RegionUpdateRequest $request
     * @param Region              $region
     *
     * @return \Illuminate\Http\Response
     */
    public function update(RegionUpdateRequest $request, Region $region)
    {
        $region->update($request->all());
        return redirect()->route('admin.regions.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param Region  $region
     * @param Request $request
     *
     * @return \Illuminate\Http\Response
     */
    public function destroy(Region $region, Request $request)
    {
        try {
            $region->delete();
        } catch (\Throwable $e) {
            $request->session()->flash('region_admin', 'Unsuccessful deleting!');
        }
        return redirect()->route('admin.regions.index');
    }
}

resources/views/admin/regions/create.blade.php
@extends('admin.layouts.main')
@section('title', __('Create new region'))
@section('content')
    <form method="POST" action="{{ route('admin.regions.store') }}">
        @csrf
        <div class="form-group {{ $errors->has('title') ? ' has-error' : '' }}">
            <label for="title" class="col-form-label">@lang('Title')</label>
            <input id="title" class="form-control" name="title" value="{{ old('title') }}">
            @if ($errors->has('title'))
                <span class="text-danger"><strong>{{ $errors->first('title') }}</strong></span>
            @endif
        </div>
        <div class="form-group {{ $errors->has('status') ? ' has-error' : '' }}">
            <label for="status">@lang('Status')</label>
            <select name="status" class="form-control" id="status">
                <option value="">Select one--</option>
                @foreach ($statuses as $status)
                    <option value="{{ $status }}"{{ $status === old('status') ? ' selected' : '' }}>@lang($status)</option>
                @endforeach
            </select>
            @if ($errors->has('status'))
                <span class="text-danger"><strong>{{ $errors->first('status') }}</strong></span>
            @endif
        </div>
        <div class="form-group">
            <button type="submit" class="btn btn-primary">@lang('Save')</button>
        </div>
    </form>
@stop

resources/views/admin/regions/edit.blade.php
@extends('admin.layouts.main')
@section('title', __('Update region'))
@section('content')
    <form method="POST" action="{{ route('admin.regions.update', $region) }}">
        @csrf
        @method('PUT')
        <div class="form-group {{ $errors->has('title') ? ' has-error' : '' }}">
            <label for="title" class="col-form-label">@lang('Title')</label>
            <input id="title" class="form-control" name="title" value="{{ old('title', $region->title) }}">
            @if ($errors->has('title'))
                <span class="text-danger"><strong>{{ $errors->first('title') }}</strong></span>
            @endif
        </div>
        <div class="form-group {{ $errors->has('status') ? ' has-error' : '' }}">
            <label for="status">@lang('Status')</label>
            <select name="status" class="form-control" id="status">
                <option value="">Select one--</option>
                @foreach ($statuses as $status)
                    <option value="{{ $status }}"{{ $status === old('status', $region->status) ? ' selected' : '' }}>@lang($status)</option>
                @endforeach
            </select>
            @if ($errors->has('status'))
                <span class="text-danger"><strong>{{ $errors->first('status') }}</strong></span>
            @endif
        </div>
        <div class="form-group">
             <button type="submit" class="btn btn-success">@lang('Update')</button>
        </div>
    </form>
@stop

resources/views/admin/regions/index.blade.php
@extends('admin.layouts.main')
@section('title', __('Regions'))
@section('content')
    <div class="form-group">
        <a href="{{route('admin.regions.create')}}" class="btn btn-primary">@lang('Create new region')</a>
    </div>
    @component('admin.components.alert', ['name' => 'region_admin'])@endcomponent
    <div class="card mb-3">
        <h4>@lang('Filter')</h4>
        <div class="card-body">
            <form action="?" method="GET">
                <div class="row">
                    <div class="col-sm-1">
                        <div class="form-group">
                            <label for="id" class="col-form-label">@lang('ID')</label>
                            <input id="id" class="form-control" name="id" value="{{ request('id') }}">
                        </div>
                    </div>
                    <div class="col-sm-3">
                        <div class="form-group">
                            <label for="title" class="col-form-label">@lang('Title')</label>
                            <input id="title" class="form-control" name="title" value="{{ request('title') }}">
                        </div>
                    </div>
                    <div class="col-sm-2">
                        <div class="form-group">
                            <label for="status" class="col-form-label">@lang('Status')</label>
                            <select id="status" class="form-control" name="status">
                                <option value=""></option>
                                @foreach ($statuses as $value)
                                    <option value="{{ $value }}"{{ $value === request('status') ? ' selected' : '' }}>{{ __($value) }}</option>
                                @endforeach;
                            </select>
                        </div>
                    </div>
                    <div class="col-sm-1">
                        <div class="form-group">
                            <label class="col-form-label">&nbsp;</label><br/>
                            <button type="submit" class="btn btn-primary">@lang('Search')</button>
                        </div>
                    </div>
                    <div class="col-sm-1">
                        <div class="form-group">
                            <label class="col-form-label">&nbsp;</label><br/>
                            <a href="{{request()->url()}}">
                                <button name="clear-form" value="1" type="button"
                                        class="btn btn-warning">@lang('Clear')</button>
                            </a>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
    @if (!$regions->isEmpty())
        <table class="table table-bordered table-striped">
            <thead>
            <tr>
                <th>@sortablelink('id', __('Id'))</th>
                <th>@sortablelink('title', __('Title'))</th>
                <th>@sortablelink('status', __('Status'))</th>
            </tr>
            </thead>
            <tbody>
            @foreach ($regions as $region)
                <tr>
                    <td>{{ $region->id }}</td>
                    <td>{{ $region->title }}</td>
                    <td>
                        <span class="badge {{$region->isActive() ? 'label-primary' : 'label-default'}}">{{ __($region->status) }}</span>
                    </td>
                    <td><a href="{{route('admin.regions.edit', $region->id)}}">
                            <span class="glyphicon glyphicon-pencil"></span>
                        </a>
                        <form style="display:inline-block" method="POST"
                              action="{{ route('admin.regions.destroy', $region) }}" class="mr-1">
                            @csrf
                            @method('DELETE')
                            <button class="btn-noneborder" onclick="return confirm('{{__('Are you sure?')}}')">
                                <a><span class="glyphicon glyphicon-trash"></span></a>
                            </button>
                        </form>
                    </td>
                </tr>
            @endforeach
            </tbody>
        </table>
        {!! $regions->appends(Request::except('page'))->render() !!}
    @else
        @lang('There are no regions')
    @endif
@stop