routes/web.php
<?php

use Illuminate\Support\Facades\Auth;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get(
    '/', function () {
    return view('welcome');
}
);

Route::group(
    [
        'namespace' => 'Admin',
        'prefix'    => 'admin',
        'as'        => 'admin.',

    ], function () {
        Auth::routes();
        Route::group(
            [
                'middleware' => [
                    'auth:admin',
                ],
            ], function () {
            Route::get('/', 'AdvertController@index');
            Route::any('users/find', 'UserController@find')->name('users.find');
            Route::post('adverts/destroy-photo/', 'AdvertController@destroyPhoto')->name('adverts.destroyPhoto');
            Route::resource('adverts', 'AdvertController');
            Route::resource('users', 'UserController');
            Route::resource('regions', 'RegionController');
            Route::resource('categories', 'CategoryController');
        }
    );
}
);

Route::group(
    [
        'namespace' => 'Frontend',
        //'prefix' => 'frontend',
        'as'        => 'frontend.'
        //'middleware' => 'auth'
    ], function () {
    Auth::routes();
    Route::get('/', 'SiteController@index')->name('index');
    Route::get('/feedback', 'SiteController@feedback')->name('feedback');
    Route::post('/feedback', 'SiteController@sendFeedback')->name('send-feedback');
    Route::post('region/session', 'SiteController@session')->name('session');
    Route::get('search', 'AdvertController@search')->name('adverts.search');
    Route::get('{type}/{category?}', 'AdvertController@index')
        ->where(
            [
                'type' => 'donate|receive',
                'category' => '(\w|-)+',
            ]
        )
        ->name('adverts.index');
    Route::resource('adverts', 'AdvertController')->only(
        [
            'show',
        ]
    );
    Route::resource('advert-user', 'AdvertUserController');
    Route::delete('advert-user/delete-photo/{photo}', 'AdvertUserController@deletePhoto')->name(
        'advert-user.delete-photo'
    );
    Route::resource('favorites', 'FavoriteController');
}
);

app/Http/Controllers/Frontend/AdvertController.php
<?php

namespace App\Http\Controllers\Frontend;

use App\Models\frontend\Advert;
use App\Http\Controllers\Controller;
use App\Http\Services\AdvertService;
use App\Http\Services\CategoryService;
use App\Http\Services\RegionService;
use App\Models\frontend\Category;
use Auth;
use Illuminate\Http\Request;

/**
 * Class AdvertController
 *
 * @package App\Http\Controllers\Frontend
 * @author  Dimus <iron@te.net.ua>
 */
class AdvertController extends Controller
{
    /**
     * Advert service instance
     * @var \App\Http\Services\AdvertService
     */
    private $_advertService;
    /**
     * Region service instance
     * @var \App\Http\Services\RegionService
     */
    private $_regionService;
    /**
     * Category service instance
     * @var \App\Http\Services\CategoryService
     */
    private $_categoryService;
    /**
     * Favorites service instance
     * @var \App\Http\Controllers\Frontend\FavoritesService
     */
    private $_favoriteService;

    /**
     * RegionController constructor.
     *
     * @param AdvertService    $advertService   instance
     * @param RegionService    $regionService   instance
     * @param FavoritesService $favoriteService instance
     * @param CategoryService  $categoryService instance
     */
    public function __construct(
        AdvertService $advertService,
        RegionService $regionService,
        FavoritesService $favoriteService,
        CategoryService $categoryService
    ) {
        $this->_advertService = $advertService;
        $this->_regionService = $regionService;
        $this->_categoryService = $categoryService;
        $this->_favoriteService = $favoriteService;
    }

    /**
     * Index action
     *
     * @param string                             $type
     * @param \App\Models\frontend\Category|null $category
     *
     * @return array|\Illuminate\Contracts\View\Factory|\Illuminate\View\View|mixed
     */
    public function index($type, ?Category $category)
    {
        $regionId = (int)session()->get('region');
        if ($regionId) {
            $region = $this->_regionService->get($regionId);
        }
        $adverts = $this->_advertService->getAllActive(
            $type,
            $regionId,
            $category->id ?? null
        );
        return view(
            'frontend.advert.index',
            [
                'region' => $region ?? null,
                'categoriesCollection' => $this->_categoryService->getAll(),
                'showRegion' => ($regionId === 0),
                'type' => $type,
                'category' => $category ?? null,
                'adverts' => $adverts,
                'seo' => [
                    'title' => isset($category)
                        ? $category->seo_title
                        : null,
                    'description' => isset($category)
                        ? $category->seo_description
                        : null,
                    'text' => isset($category)
                        ? $category->seo_text
                        : null,
                ],
            ]
        );
    }

    /**
     * Show action
     *
     * @param \App\Models\frontend\Advert $advert
     *
     * @return array|\Illuminate\Contracts\View\Factory|\Illuminate\View\View|mixed
     */
    public function show(Advert $advert)
    {
        $coords = [];
        $regionId = (int)session()->get('region');
        $query = $advert->region->title . '' . $advert->address;
        $data = \YaGeo::setQuery($query)->load();
        if ($data->getResponse()) {
            $coords[] = $data->getResponse()->getLatitude();
            $coords[] = $data->getResponse()->getLongitude();
        }
        $this->_advertService->updateViews($advert->id, 1);

        try {
            $region = $regionId
                ? $this->_regionService->get($regionId)
                : null;
        } catch (\Throwable $e) {
            session()->flash('advert', 'Region not found');
        }
        $view = $advert->type == Advert::TYPE_DONATE
            ? 'frontend.advert.view'
            : 'frontend.advert.view_receive';
        $categoriesCollection = $this->_categoryService->getAll();
        $canClose = false;
        //$canClose = $user->can('update', $advert);
        $region = $region ?? null;
        $related = $this->_advertService->getRelated($advert);
        $isFavorite = $this->_favoriteService->isFavorite($advert->id, Auth::id());

        return view(
            $view,
            compact(
                'advert',
                'region',
                'categoriesCollection',
                'canClose',
                'coords',
                'related',
                'isFavorite'
            )
        );
    }

    /**
     * Search action
     *
     * @param \Illuminate\Http\Request $request
     *
     * @return array|\Illuminate\Contracts\View\Factory|\Illuminate\View\View|mixed
     */
    public function search(Request $request)
    {
        $regionId = (int)session()->get('region');
        $categoryId = array_get($request, 'category');
        $query = array_get($request, 'q');
        $showRegion = ($regionId === 0);
        $adverts = $this->_advertService->search(
            [
                'region_id' => $regionId,
                'category_id' => $categoryId,
                'query' => $query,
            ]
        );
        return view(
            'frontend.advert.search',
            compact(
                'showRegion',
                'adverts'
            )
        );
    }
}

app/Http/Controllers/Frontend/AdvertUserController.php
<?php

namespace App\Http\Controllers\Frontend;

use App\Http\Controllers\Controller;
use App\Http\Requests\AdvertUserCreateRequest;
use App\Http\Requests\AdvertUserUpdateRequest;
use App\Http\Services\AdvertService;
use App\Http\Services\CategoryService;
use App\Http\Services\RegionService;
use App\Http\Services\UserService;
use App\Models\common\Advert;
use App\Models\common\AdvertPhoto;
use App\Models\common\User;
use Illuminate\Auth\Access\AuthorizationException;
use Illuminate\Contracts\View\Factory;
use Illuminate\Http\Request;
use Illuminate\View\View;

/**
 * AdvertController implements the CRUD actions for Advert model.
 *
 * @author Dimus <iron@te.net.ua>
 */
class AdvertUserController extends Controller
{
    /**
     * Region service instance
     *
     * @var RegionService
     */
    private $_regionService;

    /**
     * Category service instance
     *
     * @var CategoryService
     */
    private $_categoryService;

    /**
     * User service instance
     *
     * @var UserService
     */
    private $_userService;

    /**
     * Advert service instance
     *
     * @var AdvertService
     */
    private $_advertService;

    /**
     * AdvertController constructor.
     *
     * @param AdvertService   $advertService   instance
     * @param RegionService   $regionService   instance
     * @param UserService     $userService     instance
     * @param CategoryService $categoryService instance
     */
    public function __construct(
        AdvertService $advertService,
        RegionService $regionService,
        UserService $userService,
        CategoryService $categoryService
    ) {
        $this->_regionService = $regionService;
        $this->_categoryService = $categoryService;
        $this->_userService = $userService;
        $this->_advertService = $advertService;
        $this->middleware('auth');
    }

    /**
     * Index action
     *
     * @return string
     */
    public function index()
    {
        /**@var $user User */
        $user = \Auth::user();
        $opened = $this->_advertService->getOpened($user->id);
        $closed = $this->_advertService->getClosed($user->id);

        return view('frontend.advert-user.index', compact('opened', 'closed'));
    }

    /**
     * Create advert action
     *
     * @return array|Factory|View|mixed
     */
    public function create()
    {
        return view(
            'frontend.advert-user.create',
            [
                'regions'    => $this->_regionService->getAllActive(),
                'categories' => $this->_categoryService->getSubCategories(),
                'statuses'   => $this->_advertService->getUserStatuses(),
            ]
        );
    }

    /**
     * Save advert action
     *
     * @param AdvertUserCreateRequest $request instance
     *
     * @return \Illuminate\Http\RedirectResponse
     */
    public function store(AdvertUserCreateRequest $request)
    {
        $all = $request->all();
        $all['author_id'] = \Auth::id();

        try {
            $this->_advertService->saveWithPhoto(
                Advert::make(),
                $all,
                array_get($request, 'images', [])
            );
        } catch (\Throwable $e) {
            $request->session()->flash('advert', 'Error storing');
        }
        return redirect()->route('frontend.advert-user.index');
    }

    /**
     * Edit advert action
     *
     * @param Advert $advertUser instance
     *
     * @return array|Factory|View|mixed
     */
    public function edit(Advert $advertUser)
    {
        try {
            $this->authorize('update', $advertUser);
            return view(
                'frontend.advert-user.update',
                [
                    'regions'    => $this->_regionService->getAllActive(),
                    'categories' => $this->_categoryService->getSubCategories(),
                    'statuses'   => $this->_advertService->getAllStatuses(),
                    'advert'     => $advertUser,
                ]
            );
        } catch (AuthorizationException $e) {
            return abort(404);
        }
    }

    /**
     * Update advert action
     *
     * @param Advert                  $advertUser instance
     * @param AdvertUserUpdateRequest $request    instance
     *
     * @return \Illuminate\Http\RedirectResponse
     */
    public function update(Advert $advertUser, AdvertUserUpdateRequest $request)
    {
        try {
            $this->authorize('update', $advertUser);
            $all = $request->all();
            try {
                $this->_advertService->saveWithPhoto(
                    $advertUser,
                    $all,
                    array_get($request, 'images', [])
                );
            } catch (\Throwable $e) {
                $request->session()->flash('advert', 'Error update');
            }
            return redirect()->route('frontend.advert-user.index');
        } catch (AuthorizationException $e) {
            return abort(404);
        }
    }

    /**
     * Delete advert action
     *
     * @param Advert  $advertUser instance
     * @param Request $request    instance
     *
     * @return \Illuminate\Http\RedirectResponse
     */
    public function destroy(Advert $advertUser, Request $request)
    {
        try {
            $this->authorize('delete', $advertUser);
            try {
                $this->_advertService->deleteAdvert($advertUser);
                return redirect()->route('frontend.advert-user.index');
            } catch (\Throwable $e) {
                $request->session()->flash('advert', 'Error delete');
            }
            return redirect()->route('frontend.advert-user.index');
        } catch (AuthorizationException $e) {
            return abort(403, 'Unauthorized action');
        }
    }

    /**
     * Delete photo from advert action by ajax
     *
     * @param AdvertPhoto $photo   instance
     * @param Request     $request instance
     *
     * @return array
     */
    public function deletePhoto(AdvertPhoto $photo, Request $request)
    {
        if ($request->ajax()) {
            try {
                $this->authorize('deletePhoto', $photo);
                try {
                    $this->_advertService->deletePhoto($photo->title);
                    return [];
                } catch (\Throwable $e) {
                    return ['error' => "Error deleting"];
                }
            } catch (AuthorizationException $e) {
                return ['error' => "Unauthorized action"];
            }
        }
        return abort(403, 'Unauthorized action');
    }

    /*public function actionClose()
    {
    }*/
}

app/Http/Controllers/Frontend/FavoriteController.php
<?php

namespace App\Http\Controllers\Frontend;

use App\Models\common\Favorite;
use App\Http\Controllers\Controller;
use App\Http\Services\AdvertService;
use App\Http\Services\CategoryService;
use App\Http\Services\RegionService;
use Auth;

/**
 * Site controller
 *
 * @author  Dimus <iron@te.net.ua>
 */
class FavoriteController extends Controller
{
    /**
     * Region service instance
     *
     * @var RegionService
     */
    private $_regionService;
    /**
     * Advert service instance
     *
     * @var AdvertService
     */
    private $_advertService;

    /**
     * Category service instance
     *
     * @var CategoryService
     */
    private $_categoryService;
    /**
     * Favorite service instance
     *
     * @var \App\Http\Controllers\Frontend\FavoritesService
     */
    private $_favoritesService;

    /**
     * SiteController constructor.
     *
     * @param RegionService    $regionService    instance
     * @param AdvertService    $advertService    instance
     * @param CategoryService  $categoryService  instance
     * @param FavoritesService $favoritesService instance
     */
    public function __construct(
        RegionService $regionService,
        AdvertService $advertService,
        CategoryService $categoryService,
        FavoritesService $favoritesService
    ) {
        $this->_regionService = $regionService;
        $this->_advertService = $advertService;
        $this->_categoryService = $categoryService;
        $this->_favoritesService = $favoritesService;
        $this->middleware('auth');
    }

    /**
     * Index action
     *
     * @return array|\Illuminate\Contracts\View\Factory|\Illuminate\View\View|mixed
     */
    public function index()
    {
        $userId = \Auth::id();
        $adverts = $this->_favoritesService->getAllByUser($userId);
        return view('frontend.favorites.index', compact('adverts'));
    }

    /**
     * Store favorite action
     *
     * @param FavoritesCreateRequest $request instance
     *
     * @return bool
     */
    public function store(FavoritesCreateRequest $request)
    {
        return (string)$this->_favoritesService
            ->create($request->get('advert_id', 0), Auth::id());
    }

    /**
     * Destroy action
     *
     * @param integer                  $favoriteId id
     * @param \Illuminate\Http\Request $request    instance
     *
     * @return \Illuminate\Http\RedirectResponse|string
     */
    public function destroy($favoriteId, \Illuminate\Http\Request $request)
    {
        try {
            $result = Favorite::where('advert_id', '=', $favoriteId)
                ->where('user_id', '=', Auth::id())
                ->delete();

        } catch (\Exception $e) {
            $result = false;
        }
        if ($request->ajax()) {
            return (string)$result;
        } else {
            return redirect()->route('frontend.favorites.index');
        }
    }
}

resources/views/frontend/advert-user/_categories_select.blade.php
@php
    $categoriesIndexed = array_index($categories, null, 'parent.title');
@endphp

<div class="ads-category form-group {{ $errors->has('category_id') ? ' has-error' : '' }}"  id="">
    @php
        $i = 1;
    @endphp
    @foreach ($categoriesIndexed as $parentTitle => $subRows)
        @php
            if ($i % 2 == 0) {
                $colOuterClass = 7;
                $colInnerClass = 4;
            } else {
                $colOuterClass = 5;
                $colInnerClass = 6;
            }
            $cols = ($colOuterClass == 7) ? 3 : 2;
            $subRows = array_chunk($subRows, $cols);
        @endphp

    <div class="comments__field col-sm-{{ $colOuterClass }}">
        <div class="ads-category__title">{{ $parentTitle }}</div>
        <div class="row ads-category__categories">
            @foreach ($subRows as $index => $rows)
            <div class="col-sm-{{$colInnerClass}} ">
                @foreach ($rows as $column)
                <div class="ads-category__item">
                    <label class="label-check label-uncheck js-label-check {{ $column->id == old('category_id', $advert->category_id ?? null) ? 'active' : '' }}">{{ $column->title }}
                        <input type="radio"
                               {{ $column->id == old('category_id', $advert->category_id ?? null) ? 'checked' : '' }}
                        name="category_id"
                               value="{{ $column->id }}">
                    </label>
                </div>
                    @endforeach
            </div>
                @endforeach
        </div>
    </div>
    @php  $i++ @endphp
    @endforeach
    <div class="clearfix"></div>
    @if ($errors->has('category_id'))
        <span class="text-danger"><strong>{{ $errors->first('category_id') }}</strong></span>
    @endif
    <div class="clearfix"></div>
</div>

resources/views/frontend/advert-user/_image_loader.blade.php
<div id="photo_loader" class="upload-previews form-group">
    <label class="col-sm-2 form-label">Фото</label>
    <div class="col-sm-5">
        <div class="form-group">
            <div class="photo_loader_photos">
                @php $advert = $advert ?? [] @endphp
                @foreach (array_get($advert, 'photos', []) as $index => $photo)
                    @php
                        $url = url("/imagecache/custom/{$photo->title}");
                    @endphp
                    <div class="photo_loader_item">
                        <span class="photo_loader_img" style="background-image: url('{{$url}}')"></span>
                        <div class="photo_loader_del"
                             data-delete-photo='{{route('frontend.advert-user.delete-photo', $photo)}}'>
                            <span class="photo_loader_del_icon"></span>
                        </div>
                    </div>
                @endforeach

                <div class="photo_loader_item photo_loader_item_template">
                    <span class="photo_loader_img"></span>
                    <div class="photo_loader_del" data-delete-photo>
                        <span class="photo_loader_del_icon"></span>
                    </div>
                </div>
                <div class="photo_loader_item photo_loader_item_add"
                {{count(array_get($advert, 'photos', [])) >= 8 ? ' style="display: none;"' : ''}}>
                    <div class="photo_loader_add" data-upload-photo>
                        <div class="photo_loader_add__icon"></div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

resources/views/frontend/advert-user/_list.blade.php
@php
    $file = array_get($model, 'photos.0');
    $url = $file ? url("/imagecache/custom/{$file->title}") : url('/img/dummy.png');
@endphp

<div class="col-sm-4 col-md-3">
    <div class="product-item">
        <a class="product-item__img" href="{{route('frontend.advert-user.edit', $model)}}">
            <img src="{{ $url }}">
        </a>
        <div class="product-item__desc">
            <a class="product-item__title"
               href="{{route('frontend.advert-user.edit', $model)}}">{{$model->title }}</a>
            <div class="clearfix">
                <span class="product-item__date fleft">
                      {{ $model->created_at->formatLocalized('%d %b %Y') }}
                </span>
                <span class="product-metadata__views fright">
                    {{(int)$model->views }}
                </span>
            </div>
        </div>
        @if ($isClosed)
            <form action="{{route('frontend.advert-user.destroy', $model)}}" id="{{$model->id}}" method="post">
                @csrf
                @method('delete')
                <button type="submit" class="btn btn-default" onclick="return confirm('Вы уверены?')">Удалить</button>
            </form>
        @endif
    </div>
</div>

resources/views/frontend/advert-user/create.blade.php
@extends('frontend.layouts.create_update', ['advert_type' =>  \App\Models\common\Advert::TYPE_DONATE])
@section('title', 'Добавить объявление')

@section('content')
    <div class="advert-create">
        @php
            $categoriesIndexed = array_index($categories, null, 'parentTitle');
        @endphp
        <form method="POST" action="{{route('frontend.advert-user.store')}}" enctype="multipart/form-data" class="profile-form form-horizontal" data-name="">
            @csrf
            <div class="container">
                <input type="radio" {{old('type', 'donate') == \App\Models\common\Advert::TYPE_DONATE ? 'checked' : ''}} id="radio-give" class="hidden" name="type" value="donate" data-ads-type="give">
                <input type="radio" {{old('type') == \App\Models\common\Advert::TYPE_RECEIVE ? 'checked' : ''}} id="radio-get" class="hidden" name="type" value="receive" data-ads-type="get">

                <div class="form-group {{ $errors->has('author_name') ? ' has-error' : '' }}">
                    <label class="col-sm-2 form-label" for="author_name">Имя</label>
                    <div class="col-sm-3">
                        <input type="text" id="author_name" class="form-field" name="author_name" value="{{ old('author_name') }}" maxlength="255" aria-required="true">
                        @if ($errors->has('author_name'))
                            <span class="text-danger"><strong>{{ $errors->first('author_name') }}</strong></span>
                        @endif
                    </div>
                </div>

                <div class="form-group {{ $errors->has('author_phone') ? ' has-error' : '' }}">
                    <label class="col-sm-2 form-label" for="author_phone">Телефон</label>
                    <div class="col-sm-3">
                        <input type="text" id="author_phone" class="form-field" name="author_phone" value="{{ old('author_phone') }}" aria-required="true">
                        @if ($errors->has('author_phone'))
                            <span class="text-danger"><strong>{{ $errors->first('author_phone') }}</strong></span>
                        @endif
                    </div>
                </div>

                <div class="form-group {{ $errors->has('author_email') ? ' has-error' : '' }}">
                    <label class="col-sm-2 form-label" for="author_email">Email</label>
                    <div class="col-sm-3">
                        <input type="text" id="author_email" class="form-field" name="author_email" value="{{ old('author_email') }}" maxlength="255">
                        @if ($errors->has('author_email'))
                            <span class="text-danger"><strong>{{ $errors->first('author_email') }}</strong></span>
                        @endif
                    </div>
                </div>

                <div class="form-group {{ $errors->has('region_id') ? ' has-error' : '' }}">
                    <label class="col-sm-2 form-label" for="region_id">Город</label>
                    <div class="col-sm-3">
                        <select id="region_id" class="js-select" name="region_id" aria-required="true">
                            <option value="">Select one--</option>
                            @foreach ($regions as $region)
                                <option value="{{$region->id}}"{{ $region->id == old('region_id') ? ' selected' : '' }}>{{$region->title}}</option>
                            @endforeach
                        </select>
                        @if ($errors->has('region_id'))
                            <span class="text-danger"><strong>{{ $errors->first('region_id') }}</strong></span>
                        @endif
                    </div>
                </div>
                <div class="line"></div>
                @include('frontend.advert-user._categories_select')
                <div class="line"></div>
                <div class="form-group {{ $errors->has('title') ? ' has-error' : '' }}">
                    <label class="col-sm-2 form-label" for="title">Название</label>
                    <div class="col-sm-5">
                        <input type="text" id="title" class="form-field" name="title" value="{{old('title')}}" maxlength="50" aria-required="true">
                        @if ($errors->has('title'))
                            <span class="text-danger"><strong>{{ $errors->first('title') }}</strong></span>
                        @endif
                    </div>
                </div>
                <div class="form-group {{ $errors->has('description') ? ' has-error' : '' }}">
                    <label class="col-sm-2 form-label" for="description">Описание</label>
                    <div class="col-sm-5">
                        <textarea id="description" class="form-field form-field_textarea-default" name="description" rows="6" aria-required="true">{{old('description')}}</textarea>
                        @if ($errors->has('description'))
                            <span class="text-danger"><strong>{{ $errors->first('description') }}</strong></span>
                        @endif
                    </div>
                </div>
                <div class="form-group {{ $errors->has('address') ? ' has-error' : '' }}">
                    <label class="col-sm-2 form-label" for="address">Адрес</label>
                    <div class="col-sm-5">
                        <input type="text" id="address" class="form-field" name="address" value="{{old('address')}}">
                        @if ($errors->has('address'))
                            <span class="text-danger"><strong>{{ $errors->first('address') }}</strong></span>
                        @endif
                    </div>
                </div>
                <div class="form-group {{ $errors->has('status') ? ' has-error' : '' }}">
                    <label class="col-sm-2 form-label" for="status">Статус</label>
                    <div class="col-sm-5">
                        <div class="ik_select">
                            <select id="status" class="js-select" name="status" aria-required="true">
                                <option value="">Select one--</option>
                                @foreach ($statuses as $status)
                                    <option value="{{$status}}"{{ $status == old('status') ? ' selected' : '' }}>{{$status}}</option>
                                @endforeach
                            </select>
                        </div>
                        @if ($errors->has('status'))
                            <span class="text-danger"><strong>{{ $errors->first('status') }}</strong></span>
                        @endif
                    </div>
                </div>
                {{--image loader   --}}
                @include('frontend.advert-user._image_loader')

            </div>
            <div class="form-footer">
                <div class="container">
                    <div class="row">
                        <div class="col-sm-offset-2 col-sm-3">
                            <button type="submit" class="btn btn-primary btn-lg">Опубликовать объявление</button>
                        </div>
                    </div>
                </div>
            </div>
        </form>
    </div>
@stop

resources/views/frontend/advert-user/index.blade.php
@extends('frontend.layouts.inner')
@php $title = 'Мои объявления'; @endphp
@section('title', $title)

@section('content')
    @component('common.components.alert', ['name' => 'advert'])@endcomponent
    <h1 class="title">{{$title}}</h1>
    @if ($opened->count() || $closed->count())
        <div class="profile-tabs">
            <ul class="tabs">
                <li class="active"><a href="#active" data-toggle="tab">Активные —  {{ $opened->count() }} </a></li>
                <li><a href="#closed" data-toggle="tab">Закрытые — {{ $closed->count() }}</a></li>
            </ul>
        </div>
        <div class="tab-content">
            <div class="tab-pane active" id="active">
                <div class="row catalog-list">
                    @foreach ($opened as $advert)
                        @include('frontend.advert-user._list', ['model' => $advert, 'isClosed' => false])
                    @endforeach
                </div>
            </div>
            <div class="tab-pane" id="closed">
                <div class="row catalog-list">
                    @foreach ($closed as $advert)
                        @include('frontend.advert-user._list', ['model' => $advert, 'isClosed' => true])
                    @endforeach
                </div>
            </div>
        </div>
    @else
        <p>У вас пока нет объявлений</p>
    @endif


@stop