routes/web.php
<?php

use Illuminate\Support\Facades\Auth;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get(
    '/', function () {
    return view('welcome');
}
);

Route::group(
    [
        'namespace' => 'Admin',
        'prefix'    => 'admin',
        'as'        => 'admin.',

    ], function () {
        Auth::routes();
        Route::group(
            [
                'middleware' => [
                    'auth:admin',
                ],
            ], function () {
            Route::get('/', 'AdvertController@index');
            Route::any('users/find', 'UserController@find')->name('users.find');
            Route::post('adverts/destroy-photo/', 'AdvertController@destroyPhoto')->name('adverts.destroyPhoto');
            Route::resource('adverts', 'AdvertController');
            Route::resource('users', 'UserController');
            Route::resource('regions', 'RegionController');
            Route::resource('categories', 'CategoryController');
        }
    );
}
);

Route::group(
    [
        'namespace' => 'Frontend',
        //'prefix' => 'frontend',
        'as'        => 'frontend.'
        //'middleware' => 'auth'
    ], function () {
    Auth::routes();
    Route::get('/', 'SiteController@index')->name('index');
    Route::get('/feedback', 'SiteController@feedback')->name('feedback');
    Route::post('/feedback', 'SiteController@sendFeedback')->name('send-feedback');
    Route::post('region/session', 'SiteController@session')->name('session');
    Route::get('search', 'AdvertController@search')->name('adverts.search');
    Route::get('{type}/{category?}', 'AdvertController@index')
        ->where(
            [
                'type' => 'donate|receive',
                'category' => '(\w|-)+',
            ]
        )
        ->name('adverts.index');
    Route::resource('adverts', 'AdvertController')->only(
        [
            'show',
        ]
    );
    Route::resource('advert-user', 'AdvertUserController');
    Route::delete('advert-user/delete-photo/{photo}', 'AdvertUserController@deletePhoto')->name(
        'advert-user.delete-photo'
    );
    Route::resource('favorites', 'FavoriteController');
}
);

app/Models/common/Category.php
<?php

namespace App\Models\common;

use Cviebrock\EloquentSluggable\Sluggable;
use Illuminate\Contracts\Pagination\LengthAwarePaginator;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Collection;
use Illuminate\Database\Eloquent\Model;
use Kyslik\ColumnSortable\Sortable;

/**
 * App\Models\common\Category
 *
 * @property int                             $id
 * @property string                          $title
 * @property string                          $slug
 * @property string|null                     $seo_title
 * @property string|null                     $seo_description
 * @property string|null                     $seo_text
 * @property int|null                        $parent_id
 * @property \Illuminate\Support\Carbon|null $created_at
 * @property \Illuminate\Support\Carbon|null $updated_at
 *
 * @property-read Collection|Category[]      $children
 * @property-read Category|null              $parent
 * @mixin         \Eloquent
 *
 * @author Dimus <iron@te.net.ua>
 */
class Category extends Model
{
    use Sluggable;
    use Sortable;

    /**
     * Fillable attr
     *
     * @var array
     */
    protected $fillable = [
        'title', 'parent_id', 'seo_title', 'seo_description', 'seo_text',
    ];
    /**
     * Sortable attr
     *
     * @var array
     */
    public $sortable = ['id', 'title', 'parent_id'];

    /**
     * Search category
     *
     * @param array $params   search params
     * @param bool  $sortable flag
     * @param null  $paginate categories per page
     *
     * @return LengthAwarePaginator|Builder[]|Collection
     */
    public static function search($params, $sortable = true, $paginate = null)
    {
        $model = new self();

        if ($sortable) {
            $query = self::sortable()->with('parent');
        } else {
            $query = $model->newQuery();
        }
        if ($value = array_get($params, 'id')) {
            $query->where('id', $value);
        }
        if ($value = array_get($params, 'title')) {
            $query->where('title', $value);
        }
        if ($value = array_get($params, 'parent_id')) {
            $query->where('parent_id', $value);
        }
        if ($paginate) {
            return $query->paginate($paginate);
        } else {
            return $query->get();
        }
    }

    /**
     * Scope
     *
     * @param Builder $query instance
     *
     * @return mixed
     */
    public function scopeTopLevel(Builder $query)
    {
        return $query->whereNull('parent_id');
    }

    /**
     * Return the sluggable configuration array for this model.
     *
     * @return array
     */
    public function sluggable()
    {
        return [
            'slug' => [
                'source' => 'title',
            ],
        ];
    }

    /**
     * Get related parent
     *
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function parent()
    {
        return $this->belongsTo(Category::class, 'parent_id');
    }

    /**
     * Get related children
     *
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function children()
    {
        return $this->hasMany(Category::class, 'parent_id');
    }
}

app/Models/frontend/Category.php
<?php

namespace App\Models\frontend;

/**
 * Class Category
 *
 * @package App\Models\frontend
 * @author  Dimus <iron@te.net.ua>
 */
class Category extends \App\Models\common\Category
{
    /**
     * Get the route key for the model.
     *
     * @return string
     */
    public function getRouteKeyName()
    {
        return 'slug';
    }
}

app/Http/Controllers/Admin/CategoryController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Models\common\Category;
use App\Http\Controllers\Controller;
use App\Http\Requests\CategoryCreateRequest;
use App\Http\Requests\CategoryUpdateRequest;

use App\Http\Services\CategoryService;

use Illuminate\Http\Request;

/**
 * Class CategoryController
 *
 * @package App\Http\Controllers\Admin
 * @author  Dimus <iron@te.net.ua>
 */
class CategoryController extends Controller
{
    /**
     * Category service instance
     * @var \App\Http\Services\CategoryService
     */
    private $_categoryService;

    /**
     * RegionController constructor.
     *
     * @param CategoryService $categoryService instance
     */
    public function __construct(CategoryService $categoryService)
    {
        $this->_categoryService = $categoryService;
    }

    /**
     * Display a listing of the resource.
     *
     * @param Request $request
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $parents = $this->_categoryService->getTopCategories();
        $categories = Category::search($request, true, 15);
        return view('admin.categories.index', compact('categories', 'parents'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $parents = $this->_categoryService->getTopCategories();
        return view('admin.categories.create', compact('parents'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param CategoryCreateRequest $request
     *
     * @return \Illuminate\Http\Response
     */
    public function store(CategoryCreateRequest $request)
    {
        Category::create(
            [
                'title' => $request->title,
                'parent_id' => $request->parent_id,
            ]
        );
        return redirect()->route('admin.categories.index');
    }

    /**
     * Display the specified resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function show()
    {
        return view('admin.categories.show');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param Category $category
     *
     * @return \Illuminate\Http\Response
     */
    public function edit(Category $category)
    {
        $parents = $this->_categoryService->getTopCategories($category->id);
        return view('admin.categories.edit', compact('parents', 'category'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param CategoryUpdateRequest $request
     * @param Category              $category
     *
     * @return \Illuminate\Http\Response
     */
    public function update(CategoryUpdateRequest $request, Category $category)
    {
        $category->slug = null;
        $category->update($request->all());
        return redirect()->route('admin.categories.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param Category $category
     * @param Request  $request
     *
     * @return \Illuminate\Http\Response
     */
    public function destroy(Category $category, Request $request)
    {
        try {
            $category->delete();
        } catch (\Exception $e) {
            $request->session()->flash('category', 'Unsuccessful deleting!');
        }
        return redirect()->route('admin.categories.index');
    }
}

resources/views/admin/categories/create.blade.php
@extends('admin.layouts.main')
@section('title', __('Create new category'))
@section('content')

    <form method="POST" action="{{ route('admin.categories.store') }}">
        @csrf
        <div class="form-group {{ $errors->has('title') ? ' has-error' : '' }}">
            <label for="title" class="col-form-label">@lang('Title')</label>
            <input id="title" class="form-control" name="title" value="{{ old('title') }}">
            @if ($errors->has('title'))
                <span class="text-danger"><strong>{{ $errors->first('title') }}</strong></span>
            @endif
        </div>
        <div class="form-group {{ $errors->has('parent_id') ? ' has-error' : '' }}">
            <label for="parent_id">@lang('Parent category')</label>
            <select name="parent_id" class="form-control" id="parent_id">
                <option value="">Select one--</option>
                @foreach ($parents as $parent)
                    <option value="{{ $parent->id }}"{{ $parent->id == old('parent_id') ? ' selected' : '' }}>@lang($parent->title)</option>
                @endforeach
            </select>
            @if ($errors->has('parent_id'))
                <span class="text-danger"><strong>{{ $errors->first('parent_id') }}</strong></span>
            @endif
        </div>
        <div class="form-group {{ $errors->has('seo_title') ? ' has-error' : '' }}">
            <label for="seo_title" class="col-form-label">@lang('Seo title')</label>
            <input id="seo_title" class="form-control" name="seo_title" value="{{ old('seo_title') }}">
            @if ($errors->has('seo_title'))
                <span class="text-danger"><strong>{{ $errors->first('seo_title') }}</strong></span>
            @endif
        </div>
        <div class="form-group {{ $errors->has('seo_description') ? ' has-error' : '' }}">
            <label for="seo_description" class="col-form-label">@lang('Seo description')</label>
            <textarea  rows="2" id="seo_description" class="form-control" name="seo_description" >{{ old('seo_description') }}</textarea>
            @if ($errors->has('seo_description'))
                <span class="text-danger"><strong>{{ $errors->first('seo_description') }}</strong></span>
            @endif
        </div>
        <div class="form-group {{ $errors->has('seo_text') ? ' has-error' : '' }}">
            <label for="seo_text" class="col-form-label">@lang('Seo text')</label>
            <textarea  rows="5" id="seo_text" class="form-control" name="seo_text">{{old('seo_text')}}</textarea>
            @if ($errors->has('seo_description'))
                <span class="text-danger"><strong>{{ $errors->first('seo_text') }}</strong></span>
            @endif
        </div>
        <div class="form-group">
            <button type="submit" class="btn btn-primary">@lang('Save')</button>
        </div>
    </form>
@stop

resources/views/admin/categories/edit.blade.php
@extends('admin.layouts.main')
@section('title', __('Update category'))
@section('content')
    <form method="POST" action="{{ route('admin.categories.update', $category) }}">
        @csrf
        @method('put')
        <div class="form-group {{ $errors->has('title') ? ' has-error' : '' }}">
            <label for="title" class="col-form-label">@lang('Title')</label>
            <input id="title" class="form-control" name="title" value="{{ old('title', $category->title) }}">
            @if ($errors->has('title'))
                <span class="text-danger"><strong>{{ $errors->first('title') }}</strong></span>
            @endif
        </div>
        @unless (!$category->children->isEmpty())
            <div class="form-group {{ $errors->has('parent_id') ? ' has-error' : '' }}">
                <label for="parent_id">@lang('Parent category')</label>
                <select name="parent_id" class="form-control" id="parent_id">
                    <option value="">Select one--</option>
                    @foreach ($parents as $parent)
                        <option value="{{ $parent->id }}"{{ $parent->id == old('parent_id', $category->parent_id) ? ' selected' : '' }}>@lang($parent->title)</option>
                    @endforeach
                </select>
                @if ($errors->has('parent_id'))
                    <span class="text-danger"><strong>{{ $errors->first('parent_id') }}</strong></span>
                @endif
            </div>
        @endunless
        <div class="form-group {{ $errors->has('seo_title') ? ' has-error' : '' }}">
            <label for="seo_title" class="col-form-label">@lang('Seo title')</label>
            <input id="seo_title" class="form-control" name="seo_title" value="{{ old('seo_title', $category->seo_title) }}">
            @if ($errors->has('seo_title'))
                <span class="text-danger"><strong>{{ $errors->first('seo_title') }}</strong></span>
            @endif
        </div>
        <div class="form-group {{ $errors->has('seo_description') ? ' has-error' : '' }}">
            <label for="seo_description" class="col-form-label">@lang('Seo description')</label>
            <textarea  rows="2" id="seo_description" class="form-control" name="seo_description" >{{ old('seo_description', $category->seo_description) }}</textarea>
            @if ($errors->has('seo_description'))
                <span class="text-danger"><strong>{{ $errors->first('seo_description') }}</strong></span>
            @endif
        </div>
        <div class="form-group {{ $errors->has('seo_text') ? ' has-error' : '' }}">
            <label for="seo_text" class="col-form-label">@lang('Seo text')</label>
            <textarea  rows="5" id="seo_text" class="form-control" name="seo_text">{{old('seo_text', $category->seo_text)}}</textarea>
            @if ($errors->has('seo_description'))
                <span class="text-danger"><strong>{{ $errors->first('seo_text') }}</strong></span>
            @endif
        </div>
        <div class="form-group">
            <button type="submit" class="btn btn-primary">@lang('Save')</button>
        </div>
    </form>
@stop

resources/views/admin/categories/index.blade.php
@extends('admin.layouts.main')
@section('title', __('Categories'))
@section('content')
    <div class="form-group">
        <a href="{{route('admin.categories.create')}}" class="btn btn-primary">@lang('Create new category')</a>
    </div>
    @component('admin.components.alert', ['name' => 'category'])@endcomponent
    <div class="card mb-3">
        <h4>@lang('Filter')</h4>
        <div class="card-body">
            <form action="?" method="GET">
                <div class="row">
                    <div class="col-sm-1">
                        <div class="form-group">
                            <label for="id" class="col-form-label">@lang('ID')</label>
                            <input id="id" class="form-control" name="id" value="{{ request('id') }}">
                        </div>
                    </div>
                    <div class="col-sm-3">
                        <div class="form-group">
                            <label for="title" class="col-form-label">@lang('Title')</label>
                            <input id="title" class="form-control" name="title" value="{{ request('title') }}">
                        </div>
                    </div>
                    <div class="col-sm-2">
                        <div class="form-group">
                            <label for="parent_id" class="col-form-label">@lang('Parent category')</label>
                            <select id="parent_id" class="form-control" name="parent_id">
                                <option value=""></option>
                                @foreach ($parents as $parent)
                                    <option value="{{ $parent->id }}"{{ $parent->id === request('parent_id') ? ' selected' : '' }}>{{ $parent->title}}</option>
                                @endforeach;
                            </select>
                        </div>
                    </div>
                    <div class="col-sm-1">
                        <div class="form-group">
                            <label class="col-form-label">&nbsp;</label><br/>
                            <button type="submit" class="btn btn-primary">@lang('Search')</button>
                        </div>
                    </div>
                    <div class="col-sm-1">
                        <div class="form-group">
                            <label class="col-form-label">&nbsp;</label><br/>
                            <a href="{{request()->url()}}">
                                <button name="clear-form" value="1" type="button"
                                        class="btn btn-warning">@lang('Clear')</button>
                            </a>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
    @if (!$categories->isEmpty())
        <table class="table table-bordered table-striped">
            <thead>
            <tr>
                <th>@sortablelink('id', __('Id'))</th>
                <th>@sortablelink('title', __('Title'))</th>
                <th>@sortablelink('parent_id', __('Parent category'))</th>
            </tr>
            </thead>
            <tbody>

            @foreach ($categories as $category)
                <tr>
                    <td>{{ $category->id }}</td>
                    <td>{{ $category->title }}</td>
                    <td>{{array_get($category, 'parent.title', '')}}</td>
                    <td><a href="{{route('admin.categories.edit', $category->id)}}">
                            <span class="glyphicon glyphicon-pencil"></span>
                        </a>
                        <form style="display:inline-block" method="POST"
                              action="{{ route('admin.categories.destroy', $category) }}" class="mr-1">
                            @csrf
                            @method('DELETE')
                            <button class="btn-noneborder" onclick="return confirm('{{__('Are you sure?')}}')">
                                <a><span class="glyphicon glyphicon-trash"></span></a>
                            </button>
                        </form>
                    </td>
                </tr>
            @endforeach
            </tbody>
        </table>
        {!! $categories->appends(Request::except('page'))->render() !!}
    @else
        @lang('There are no categories')
    @endif
@stop