routes/web.php
<?php

use Illuminate\Support\Facades\Auth;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get(
    '/', function () {
    return view('welcome');
}
);

Route::group(
    [
        'namespace' => 'Admin',
        'prefix'    => 'admin',
        'as'        => 'admin.',

    ], function () {
        Auth::routes();
        Route::group(
            [
                'middleware' => [
                    'auth:admin',
                ],
            ], function () {
            Route::get('/', 'AdvertController@index');
            Route::any('users/find', 'UserController@find')->name('users.find');
            Route::post('adverts/destroy-photo/', 'AdvertController@destroyPhoto')->name('adverts.destroyPhoto');
            Route::resource('adverts', 'AdvertController');
            Route::resource('users', 'UserController');
            Route::resource('regions', 'RegionController');
            Route::resource('categories', 'CategoryController');
        }
    );
}
);

Route::group(
    [
        'namespace' => 'Frontend',
        //'prefix' => 'frontend',
        'as'        => 'frontend.'
        //'middleware' => 'auth'
    ], function () {
    Auth::routes();
    Route::get('/', 'SiteController@index')->name('index');
    Route::get('/feedback', 'SiteController@feedback')->name('feedback');
    Route::post('/feedback', 'SiteController@sendFeedback')->name('send-feedback');
    Route::post('region/session', 'SiteController@session')->name('session');
    Route::get('search', 'AdvertController@search')->name('adverts.search');
    Route::get('{type}/{category?}', 'AdvertController@index')
        ->where(
            [
                'type' => 'donate|receive',
                'category' => '(\w|-)+',
            ]
        )
        ->name('adverts.index');
    Route::resource('adverts', 'AdvertController')->only(
        [
            'show',
        ]
    );
    Route::resource('advert-user', 'AdvertUserController');
    Route::delete('advert-user/delete-photo/{photo}', 'AdvertUserController@deletePhoto')->name(
        'advert-user.delete-photo'
    );
    Route::resource('favorites', 'FavoriteController');
}
);

resources/views/frontend/blocks/modals/auth.blade.php
<div class="modal fade" id="modal-auth" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog modal-sm">
        <div class="modal-content">
            <div class="modal-header">
                <div class="modal-close" data-dismiss="modal" aria-hidden="true"></div>
                <ul class="modal-header__tabs tabs">
                    <li class="active"><a href="#sign-in" data-toggle="tab">Вход</a></li>
                    <li><a href="#sign-up" data-toggle="tab">Регистрация</a></li>
                </ul>
            </div>
            <div class="tab-content">
                <div class="tab-pane active" id="sign-in">
                    @include('frontend.blocks.forms.login')
                </div>
                <div class="tab-pane" id="sign-up">
                    @include('frontend.blocks.forms.register')
                </div>
            </div>
        </div>
    </div>
</div>

@push('scripts')
    <script>
        $(function () {
            $('.modalButton').click(function (e) {
                var btnType = $(this).attr('data-attr');

                if (btnType == 'reg') {
                    $('a[href="#sign-up"]').tab('show');
                } else {
                    $('a[href="#sign-in"]').tab('show');
                }
                e.preventDefault();
                $('#modal-auth').modal('show');
            });
        });
    </script>
@endpush

resources/views/frontend/blocks/modals/favorites.blade.php
<div id="added-favorite" class="modal fade" role="dialog" tabindex="-1">
    <div class="modal-dialog modal-sm">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                <div class="text-center">Обьявление добавлено в избранное</div>
            </div>
            <div class="modal-body">
            </div>
            <div class="modal-footer">
                <div class="btn btn-primary btn-long center-block" data-dismiss="modal" aria-hidden="true">OK</div>
            </div>
        </div>
    </div>
</div>
@push('scripts')
    <script>
        $(function () {
            $.ajaxSetup({
                headers: {
                    'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                }
            });
            $('.{{$btnClass}}').on('click', function (e) {
                var id = $(this).next('.item-id').val();
                if ($(this).hasClass('active')) {
                    $.post('/favorites/' + id, {_method: 'delete'})
                    .done((response) => {
                        if (response) {
                            $(this)
                            .removeClass('active');
                            if ({{$isDetail}}) {
                                $(this).text('Добавить в избранное');
                            }
                        }
                    })

                } else {
                    $.post('{{route('frontend.favorites.store')}}', {'advert_id': id})
                    .done((response) => {
                        if (response) {
                            $('#added-favorite').modal();
                            $(this)
                            .addClass('active');
                            if ({{$isDetail}}) {
                                $(this).text('В избранном');
                            }
                        }
                    })
                    .fail((response) => {
                        window.location = "{{route('frontend.login')}}"
                    })
                }
            })
        });
    </script>
@endpush

resources/views/frontend/blocks/modals/favorites_card.blade.php
<div class="modal fade modal-sm" id="added-favorite">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <div class="text-center">Обьявление добавлено в избранное</div>
            </div>
            <div class="modal-body">
            </div>
            <div class="modal-footer">
                <div class="btn btn-primary btn-long center-block" data-dismiss="modal" aria-hidden="true">OK</div>
            </div>
        </div>
    </div>
</div>

@push('scripts')
    <script>
        $(function() {
            $.ajaxSetup({
                headers: {
                    'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                }
            });
            $('.{{$btnClass}}').on('click', function(e) {
                if($(this).hasClass('active')){
                    $.post('{{route('frontend.favorites.destroy', ['id' => $id])}}').then((response) => {
                        if(response){
                            $(this)
                            .removeClass('active');
                            if($isDetail){
                                $(this).text('Добавить в избранное');
                            }

                        }
                    });
                }else{
                    $.post('{{route('frontend.favorites.create')}}', {'advert_id': $id}).then((response) => {
                        if(response){
                            $('#added-favorite').modal();
                            $(this)
                            .addClass('active');
                            if({{ $isDetail }}){
                                $(this).text('В избранном');
                            }
                        }
                    });
                }
            })
        });
    </script>
@endpush

resources/views/frontend/blocks/modals/regions.blade.php
@php
    $regions = $regions->toArray();
    array_unshift($regions, ['id' => 0, 'title' => $allRegionsLabel]);

@endphp

<div class="modal fade" id="modal-city" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog modal-sm">
        <div class="modal-content">
            <div class="modal-header">
                <div class="modal-close" data-dismiss="modal" aria-hidden="true"></div>
            </div>
            <form class="city-form form-horizontal" action="" method="post">
                @csrf
                <div class="modal-body">
                    <ul class="list-unstyled">
                        @foreach($regions as $region)
                            @php  $checkedClass = array_get($region, 'id') == array_get($selectedRegion, 'id') ? 'active' : null @endphp
                            <li>
                                <label class="label-check {{$checkedClass}}  js-label-check">{{array_get($region, 'title')}}
                                    <input type="radio" {{ $checkedClass ? 'checked' : '' }}  name="city" value="{{array_get($region, 'id')}}">
                                </label>
                            </li>
                        @endforeach
                    </ul>
                </div>
                <div class="modal-footer">
                    <button id="city-btn" class="btn btn-primary btn-long center-block" type="button">Выбрать</button>
                </div>
            </form>
        </div>
    </div>
</div>

@php
    $regionId = $selectedRegion ?: 0;
@endphp
@push('scripts')
    <script>
        $(function () {
            $.ajaxSetup({
                headers: {
                    'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                }
            });
            var button = $('#{{$elementId ?? ''}}'),
                activeRegion = $('input[value="' + {{array_get($selectedRegion, 'id')}} +'"]').parent().text();
            if (activeRegion) {
                button.text(activeRegion);
            }
            button.on('click touch', function (e) {
                e.preventDefault();
                $('#modal-city').modal('show');
            });
            $('#city-btn').on('click touch', function () {
                $('#modal-city').modal('hide');
                var key = $('.list-unstyled .active input').val();
                $.post('{{route('frontend.session')}}', {regionId: key})
                .done(function (data) {
                    window.location.reload();
                });
            });
        });
    </script>
@endpush